#!/usr/bin/env python3
"""Self-host Inter + Cinzel (latin + latin-ext subsets) to remove the external
Google Fonts dependency that produced a 404 on gstatic (rotated woff2 file).
Writes /fonts/*.woff2 and /fonts.css at repo root, then rewrites every HTML's
googleapis <link> to a local <link rel="stylesheet" href="<rel>fonts.css">.
CSS url() is relative to fonts.css (root), so per-page src paths stay constant;
only the HTML link href needs a relative prefix by directory depth.
"""
import re, os, urllib.request, glob

UA = ('Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) '
      'Chrome/120.0.0.0 Safari/537.36')
CSS_URL = ('https://fonts.googleapis.com/css2?family=Inter:wght@300;400;500;600;700'
           '&family=Cinzel:wght@400;600;700;900&display=swap')
KEEP = {'latin', 'latin-ext'}

def fetch(url, ref=None):
    h = {'User-Agent': UA}
    if ref:
        h['Referer'] = ref
    return urllib.request.urlopen(urllib.request.Request(url, headers=h), timeout=30).read()

os.makedirs('fonts', exist_ok=True)
css = fetch(CSS_URL).decode('utf-8')
# capture "/* subset */ @font-face { body }"
blocks = re.findall(r'/\*\s*([^*]+?)\s*\*/\s*@font-face\s*\{([^}]*)\}', css)
faces = []
used = set()
for subset, body in blocks:
    subset = subset.strip()
    if subset not in KEEP:
        continue
    m = re.search(r"src:\s*url\((https://[^)]+\.woff2)\)", body)
    if not m:
        continue
    url = m.group(1)
    fname = url.rsplit('/', 1)[-1]
    if fname in used:
        # reuse already-downloaded (same file for same subset across weights is unique by hash)
        local = 'fonts/' + fname
    else:
        data = fetch(url, ref='https://fonts.gstatic.com/')
        with open('fonts/' + fname, 'wb') as f:
            f.write(data)
        used.add(fname)
        local = 'fonts/' + fname
    new_body = body.replace(url, 'fonts/' + fname)
    faces.append('@font-face {\n' + new_body.strip() + '\n}')
with open('fonts.css', 'w', encoding='utf-8') as f:
    f.write('/* Self-hosted Inter + Cinzel — latin + latin-ext. Generated by _qa_fontselfhost.py */\n')
    f.write('\n'.join(faces) + '\n')
print('fonts.css written with', len(faces), 'faces;', len(used), 'woff2 files')

# Rewrite HTML files
pat_link = re.compile(r'<link[^>]*href="https://fonts\.googleapis\.com/css2\?[^"]*"[^>]*>\n?')
pat_pre = re.compile(r'<link[^>]*rel="preconnect"[^>]*>\n?')
n=0
for html in glob.glob('**/*.html', recursive=True):
    if '/.git/' in html:
        continue
    depth = html.count('/')
    rel = '../' * depth
    txt = open(html, encoding='utf-8').read()
    new = pat_link.sub(f'<link rel="stylesheet" href="{rel}fonts.css">\n', txt)
    new = pat_pre.sub('', new)
    if new != txt:
        open(html, 'w', encoding='utf-8').write(new)
        n += 1
        print('rewrote', html, 'rel=', repr(rel))
print('HTML files rewritten:', n)
